name: PipelineCompleto

on:
  push:
    branches:
      - main

permissions: 
  contents: write
  pages: write
  id_token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    enviroment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SetupPages
        uses: actions/configure-pages@v5

      - name: uploads
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

      
